### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by ashishagarwal2023** [N3RDIUM/JARVIS#15]
What's up? Congrats on 300 followers, anyways are you still working on it? I'll contribute back.
Also you got any sources where we can chat, discord or google chat? I remember you, do you remember me? (Friend of anant/sreehari/aman)

**Comment by ashishagarwal2023** [comment]
Btw I recommend you to: delete all useless repos and have your github profile professional, I just did (but keep some good things and make them professional or archive)

_Edit: having most used as html or css makes me hate up so I did this just_

**Comment by N3RDIUM** [comment]
Hey there, long time no see!
Yup, I remember all of you as if it was yesterday. We all used to work together, and now everyone went quiet. 
I'm planning on working on this project again, and it will be integrated into some of my other projects as well.
My 10th boards finish tomorrow, so I'm getting my PC back tomorrow. Are you on Discord? Gimme your username and let's talk!
Now that you mentioned it, I will clean up my GitHub profile too, It has been a long time since I last touched it.

**Comment by N3RDIUM** [comment]
Btw do you use windows? Please consider helping me out on my n3rdium/taskbar repo too, I switched to Linux and I have to work on it using a slow as heck VM.

**Comment by ashishagarwal2023** [comment]
Ok sure, yes, but let me rename my discord I'll give it soon

For now send a req to josh.266 my discord.

Yes I use windows 11. Ok sure, ofc.

**Comment by ashishagarwal2023** [comment]
New discord: ashish.agarwal @N3RDIUM 

btw i just successfully dualbooted windows 11 with ubuntu :D lets go now i got 2 os

**Comment by N3RDIUM** [comment]
I sent you a friend request on Discord.

**Comment by ashishagarwal2023** [comment]
Yes got it @N3RDIUM respond on discord

**Comment by N3RDIUM** [comment]
Closing issue...
